import openai
import os

# Load your OpenAI API key from environment variables
openai.api_key = os.getenv("OPENAI_API_KEY")

def summarize_user_log(log_text):
    """
    Takes a daily habit log and returns a summarized feedback.

    Args:
        log_text (str): A string containing the user's daily activity log.

    Returns:
        str: A summary generated by the AI, highlighting achievements and suggesting improvements.
    """
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a productivity coach. Summarize the user's day, highlight successes, and gently suggest one area of improvement."},
                {"role": "user", "content": log_text}
            ],
            temperature=0.7,
            max_tokens=300
        )
        return response['choices'][0]['message']['content']
    except Exception as e:
        return f"Error during summarization: {str(e)}"
